agent-golang:
  build: agents/golang
  # ports:
   # - "8001:8001"
agent-nodejs:
  build: agents/nodejs
  # ports:
   # - "8002:8002"
agent-php:
  build: agents/php
  # ports:
   # - "8003:8003"
agent-python:
  build: agents/python
  # ports:
   # - "8004:8004"
agent-ruby:
  build: agents/ruby
  # ports:
   # - "8005:8005"
dispatcher:
  build: dispatcher
  ports:
   - "8000:8000"
  links:
    - agent-golang:golang
    - agent-nodejs:nodejs
    - agent-php:php
    - agent-python:python
    - agent-ruby:ruby
